create table if not exists public.android_apk_downloads (
  id bigint generated by default as identity primary key,
  downloaded_at timestamptz not null default now(),
  user_agent text,
  referer text,
  source text not null default 'website'
);

create index if not exists android_apk_downloads_downloaded_at_idx
  on public.android_apk_downloads (downloaded_at desc);

alter table public.android_apk_downloads enable row level security;
