create table if not exists public.admin_notifications (
  id uuid primary key,
  admin_name text,
  admin_email text,
  notification_type text not null,
  title text not null,
  message text not null,
  html_content text,
  recipient_type text not null,
  recipient_filter jsonb not null default '{}'::jsonb,
  recipients_list text,
  recipient_count integer not null default 0,
  status text not null default 'sending',
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  tags jsonb not null default '[]'::jsonb,
  is_urgent boolean not null default false,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create table if not exists public.admin_notification_logs (
  id bigint generated by default as identity primary key,
  notification_id uuid not null references public.admin_notifications(id) on delete cascade,
  user_id uuid,
  user_email text not null,
  status text not null,
  error_message text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create index if not exists admin_notifications_created_at_idx
  on public.admin_notifications (created_at desc);

create index if not exists admin_notification_logs_notification_id_idx
  on public.admin_notification_logs (notification_id);

alter table public.admin_notifications enable row level security;
alter table public.admin_notification_logs enable row level security;